[package]
name = "jpki"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.0-alpha.10"
yasna = "0.4"
x509-certificate = "0.4"

[workspace]
members = [
    "android",
    "bridge"
]
