[package]
name = "jpki-cli"
description = "Read certificates, sign and verify documents using your JPKI card."
version = "0.1.8"
license = "MIT"
homepage = "https://github.com/siketyan/jpki-rs"
repository = "https://github.com/siketyan/jpki-rs.git"
authors = ["Naoki Ikeguchi <me@s6n.jp>"]
readme = "../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }
dialoguer = "0.10"
hex = "0.4"
jpki = { version = "0.1", path = ".." }
pcsc = "2.7"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
