[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-L./android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/31"]

[target.aarch64-linux-android]
rustflags = ["-C", "link-args=-L./android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/31"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-args=-L./android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-android/31"]
